Add node images
get-bridge/docker-base-images pull request #77
Opened 2023-04-05 22:15 UTC by djbender

Adds node versions with their default npm:
- 8
- 10
- 12
- 14
- 16
- 18
- 19

There's also `fat`, `yarn`, and `fat-yarn` flavors. Yarn is pinned to v1.

2023-04-10 19:07 UTC, raybrownco requested changes
Friggin great work. Aside from one request, I'm loving it. Thanks for doing this, Derek!

2023-04-10 19:07 UTC, raybrownco commented on node/README.md
@djbender Could you add some notes to this README explaining what the difference is between the `N`, `N-fat`, `N-yarn`, and `N-fat-yarn` images? I could probably guess and be right, but I think it'd be useful to document for people who aren't all that familiar with Docker but end up here because they've got to use the images anyway.

2023-04-10 22:02 UTC, djbender commented on node/README.md
Yes! A lot of documentation in this project could definitely be improved.

2023-04-11 17:08 UTC, djbender commented
@raybrownco I've updated all the READMEs!

2023-04-11 18:11 UTC, merged